version: "3.8"

services:
  backend:
    build: ./backend_api
    ports:
      - "3000:3000"
    environment:
      - MONGO_URI=${MONGO_URI}
      - DB_NAME=${DB_NAME}
    networks:
      - app-network

  frontend:
    build: ./angular_client
    ports:
      - "4200:4200"
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge